version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: QUADMarket
      POSTGRES_USER: QUADuser
      POSTGRES_DB: QUADdb

  web:
    build: .
    command: bash -c "rm -f /quad/tmp/pids/server.pid && ./bin/rails server -b '0.0.0.0'"
    volumes:
      - .:/quad
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://QUADuser:QUADMarket@db/QUADdb
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
