default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: QUADuser
  password: QUADMarket
  host: db
  port: 5432

development:
  <<: *default
  database: QUADdb_development

test:
  <<: *default
  database: QUADdb_test

production:
  <<: *default
  database: QUADdb_production
